apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-ass.dbServiceName" . }}
  labels:
    {{- include "devops-ass.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
  selector:
    {{- include "devops-ass.dbSelectorLabels" . | nindent 4 }}
